rentalpoint_index:
    path:     /
    defaults: { _controller: "AppBundle:RentalPoint:index" }
    methods:  GET

rentalpoint_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:RentalPoint:show" }
    methods:  GET

rentalpoint_new:
    path:     /new
    defaults: { _controller: "AppBundle:RentalPoint:new" }
    methods:  [GET, POST]

rentalpoint_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:RentalPoint:edit" }
    methods:  [GET, POST]

rentalpoint_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:RentalPoint:delete" }
    methods:  DELETE
