# src/AppBundle/Resources/config/doctrine/Car.orm.yml
AppBundle\Entity\Car:
  type: entity
  table: Car
  id:
    id:
        type: integer
        generator:
          strategy: AUTO
  fields:
    model:
        type: string
        length: 255
    license_plate:
         type: string
         length: 255
         unique: true
    picture:
         type: string
         length: 255
         nullable: true
  oneToMany:
    Cars:
      targetEntity: RentalHistory
      mappedBy: Car